### ISSUE TITLE
Error in BOM

### ISSUE THREAD

**Issue by vytenisstaugaitis** [ghztomash/CVSequencer#1]
In schematic R23, R24 and R25 are 10k which I assume is correct while in BOM pdf these are under 100k

**Comment by ghztomash** [comment]
Thank you for the clarification! you should be able to use anything from 10k to 100k there. Would you have the capacity to verify that? I don't have a board at hand at the moment.

**Comment by vytenisstaugaitis** [comment]
with 100k inputs A, B, C do not work, with 10k works as intended.

**Comment by ghztomash** [comment]
@vytenisstaugaitis thank you for checking up! I will update the BOM accordingly.

**Comment by vytenisstaugaitis** [comment]
no problem :) thanks for sharing, really love it!
